[server]
addr = "localhost:50053"
[service_discovery]
name = "client"
[consul]
address = "http://127.0.0.1:8500"
[consul.health_check]
name = "client"
id = "client"
ttl = "10s"
interval_duration = "9s"